apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "owl.fullname" . }}-dask-config
  labels:
    app: {{ template "owl.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "owl.chart" . }}
    component: owl
data:
  dask.yaml: |
    {{- toYaml .Values.dask | nindent 4 }}