apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "owl.fullname" . }}-owl-config
  labels:
    app: {{ template "owl.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "owl.chart" . }}
    component: owl
data:
  owl.yaml: |
    {{- if typeIs "string" .Values.token }}
    token: {{ .Values.token | quote }}
    {{- else }}
    token: {{ randAlphaNum 64 | quote }}
    {{- end }}
    loglevel: {{ .Values.loglevel }}
    heartbeat: {{ .Values.heartbeat }}
    max_pipelines: 6
    dbi: {{ .Values.dbi }}
    prometheus: {{ .Values.prometheus }}

    env:
      OWL_SCHEDULER_SERVICE_HOST: ${OWL_SCHEDULER_SERVICE_HOST}
      OWL_SCHEDULER_SERVICE_PORT_PIPE: ${OWL_SCHEDULER_SERVICE_PORT_PIPE}
      OWL_SCHEDULER_SERVICE_PORT_LOGS: ${OWL_SCHEDULER_SERVICE_PORT_LOGS}
      OWL_SCHEDULER_SERVICE_PORT_ADMIN: ${OWL_SCHEDULER_SERVICE_PORT_ADMIN}
      OWL_API_SERVICE_HOST: ${OWL_API_SERVICE_HOST}
      OWL_API_SERVICE_PORT: ${OWL_API_SERVICE_PORT}
      OWL_IMAGE_SPEC: ${OWL_IMAGE_SPEC}

    pipeline:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      resources:
        {{- toYaml .Values.pipeline.resources | nindent 8 }}
      serviceAccountName: {{ include "owl.serviceAccountName" . }}
      volumeMounts:
        - name: dask-config
          mountPath: /etc/dask
        - name: owl-config
          mountPath: /etc/owl
      {{- with .Values.extraVolumeMounts }}
      {{- . | toYaml | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      {{- with .Values.pipeline.extraVolumeMounts }}
      {{- . | toYaml | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      volumes:
        - name: dask-config
          configMap:
            name: owl-dask-config
        - name: owl-config
          configMap:
            name: {{ include "owl.fullname" . }}-owl-config
        {{- with .Values.extraVolumes }}
        {{- . | toYaml | trimSuffix "\n" | nindent 8 }}
        {{- end }}
        {{- with .Values.pipeline.extraVolumes }}
        {{- . | toYaml | trimSuffix "\n" | nindent 8 }}
        {{- end }}

    dask:
      kubernetes:
          # See: https://github.com/dask/dask-kubernetes/blob/main/dask_kubernetes/kubernetes.yaml
          name: dask-${JOBID}-{uuid}
          scheduler-template:
            spec:
              restartPolicy: Never
              serviceAccountName: {{ include "owl.serviceAccountName" . }}
              containers:
                - name: dask-scheduler
                  image: ${DASK_IMAGE_SPEC}
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  securityContext:
                    {{- toYaml .Values.securityContext | nindent 20 }}
                  args:
                    - dask-scheduler
                  env:
                    - name: EXTRA_PIP_PACKAGES
                      value: ${EXTRA_PIP_PACKAGES}
                    - name: OMP_NUM_THREADS
                      value: 1
                    - name: OPENBLAS_NUM_THREADS
                      value: 1
                    - name: MKL_NUM_THREADS
                      value: 1
                    - name: VECLIB_MAXIMUM_THREADS
                      value: 1
                    - name: NUMEXPR_NUM_THREADS
                      value: 1
                    - name: NUMEXPR_MAX_THREADS
                      value: 1
                    - name: LOGLEVEL
                      value: ${LOGLEVEL}
                    - name: JOBID
                      value: ${JOBID}
                  volumeMounts:
                    - name: dask-config
                      mountPath: /etc/dask
                  {{- with .Values.extraVolumeMounts }}
                  {{- . | toYaml | trimSuffix "\n" | nindent 20 }}
                  {{- end }}
                  {{- with .Values.pipeline.extraVolumeMounts }}
                  {{- . | toYaml | trimSuffix "\n" | nindent 20 }}
                  {{- end }}
                  resources:
                    {{- toYaml .Values.pipeline.resources | nindent 20 }}
              volumes:
                - name: dask-config
                  configMap:
                    name: owl-dask-config
                {{- with .Values.extraVolumes }}
                {{- . | toYaml | trimSuffix "\n" | nindent 16 }}
                {{- end }}
                {{- with .Values.pipeline.extraVolumes }}
                {{- . | toYaml | trimSuffix "\n" | nindent 16 }}
                {{- end }}

          worker-template:
            spec:
              restartPolicy: Never
              containers:
                - name: dask-worker
                  image: ${DASK_IMAGE_SPEC}
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  securityContext:
                    {{- toYaml .Values.securityContext | nindent 20 }}
                  args:
                    - dask-worker
                    - --nthreads
                    - "2"
                    - --no-dashboard
                    - --memory-limit
                    - 7GB
                    - --death-timeout
                    - "60"
                  env:
                    - name: EXTRA_PIP_PACKAGES
                      value: ${EXTRA_PIP_PACKAGES}
                    - name: OMP_NUM_THREADS
                      value: 1
                    - name: OPENBLAS_NUM_THREADS
                      value: 1
                    - name: MKL_NUM_THREADS
                      value: 1
                    - name: VECLIB_MAXIMUM_THREADS
                      value: 1
                    - name: NUMEXPR_NUM_THREADS
                      value: 1
                    - name: NUMEXPR_MAX_THREADS
                      value: 1
                    - name: LOGLEVEL
                      value: ${LOGLEVEL}
                    - name: JOBID
                      value: ${JOBID}
                  volumeMounts:
                    - name: dask-config
                      mountPath: /etc/dask
                  {{- with .Values.extraVolumeMounts }}
                  {{- . | toYaml | trimSuffix "\n" | nindent 20 }}
                  {{- end }}
                  {{- with .Values.pipeline.extraVolumeMounts }}
                  {{- . | toYaml | trimSuffix "\n" | nindent 20 }}
                  {{- end }}
                  resources:
                    limits:
                      cpu: "1.75"
                      memory: 7G
                    requests:
                      cpu: 1
                      memory: 7G
              volumes:
                - name: dask-config
                  configMap:
                    name: owl-dask-config
                {{- with .Values.extraVolumes }}
                {{- . | toYaml | trimSuffix "\n" | nindent 16 }}
                {{- end }}
                {{- with .Values.pipeline.extraVolumes }}
                {{- . | toYaml | trimSuffix "\n" | nindent 16 }}
                {{- end }}