apiVersion: v1
kind: Service
metadata:
  name: {{ include "owl.fullname" . }}-scheduler
  labels:
    {{- include "owl.labels.scheduler" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 7001
      targetPort: 7001
      protocol: TCP
      name: pipe
    - port: 7002
      targetPort: 7002
      protocol: TCP
      name: logs
  selector:
    {{- include "owl.selectorLabels.scheduler" . | nindent 4 }}
