{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "owl.serviceAccountName" . }}
  labels:
    {{- include "owl.labels.scheduler" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "owl.serviceAccountName" . }}
  labels:
    {{- include "owl.labels.scheduler" . | nindent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs/status"]
  verbs: ["get"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "create", "delete", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "owl.serviceAccountName" . }}
  labels:
    {{- include "owl.labels.scheduler" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "owl.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: {{ include "owl.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
