image:
  repository: imaxt/owl-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: "0.7.1"

serviceAccount:
  create: true

loglevel: DEBUG
dbi: sqlite:////var/run/owl/sqlite.db
token: 8bgJcJEVc0QjP91beuVC5HFGea4p2ZBr
# Takes care of slow start in GKE with small number of resources
heartbeat: 60
# prometheus: http://prometheus-kube-prometheus-prometheus.monitoring:9090

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

podSecurityContext:
  fsGroup: 1000

pipeline:
  resources:
    limits:
      cpu: 500m
      memory: 500M
    requests:
      cpu: 500m
      memory: 500M

scheduler:
  resources:
    limits:
      cpu: 500m
      memory: 500M
    requests:
      cpu: 500m
      memory: 500M

api:
  resources:
    limits:
      cpu: 500m
      memory: 500M
    requests:
      cpu: 500m
      memory: 500M

dask: {}
