image:
  repository: imaxt/owl-server
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.6.1"

serviceAccount:
  create: true

loglevel: DEBUG
dbi: sqlite:////var/run/owl/sqlite.db
token: 8bgJcJEVc0QjP91beuVC5HFGea4p2ZBr
heartbeat: 60
# prometheus: http://prometheus-kube-prometheus-prometheus.monitoring:9090

# Default image runs as user and group ids 1000
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

podSecurityContext:
  fsGroup: 1000

# The resources here are for a free GCE account with very limited resources
# Increase (or leave empty for defaults) for a production environment
pipeline:
  resources:
    limits:
      cpu: 100m
      memory: 500M
    requests:
      cpu: 100m
      memory: 500M

scheduler:
  resources:
    limits:
      cpu: 100m
      memory: 500M
    requests:
      cpu: 100m
      memory: 500M

api:
  resources:
    limits:
      cpu: 100m
      memory: 500M
    requests:
      cpu: 100m
      memory: 500M

dask: {}
