image:
  repository: imaxt/owl-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: "today"

serviceAccount:
  create: true

loglevel: DEBUG
dbi: sqlite:////var/run/owl/sqlite.db
prometheus: http://prometheus-kube-prometheus-prometheus.monitoring:9090

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

pipeline:
  resources:
    limits:
      cpu: 2
      memory: 7G
    requests:
      cpu: 2
      memory: 7G
  extraVolumeMounts:
    - name: meds1a
      mountPath: /data/meds1_a/eglez
  extraVolumes:
    - name: meds1a
      hostPath:
        path: /data/meds1_a/eglez
        type: Directory

scheduler:
  resources:
    limits:
      cpu: 2
      memory: 7G
    requests:
      cpu: 2
      memory: 7G

api:
  resources:
    limits:
      cpu: 2
      memory: 7G
    requests:
      cpu: 2
      memory: 7G

dask: {}
